### ISSUE TITLE
cancel jobs

### ISSUE THREAD

**Issue by podviaznikov** [AdamClements/schejulure#3]
Hi,

Thank you for creating this library. The API looks very simple.

I saw that it's possible to cancel single job via following code:

```

(future-cancel my-running-scheduler)

```

Since I'm new to Clojure it's not obvious how to implement following case:
I want to schedule multiple jobs. On some event I want to cancel some of them.

So basically I need behavior similar to this: each job has id. I have list of all ids and I can cancel job by that id.

Do you have any ideas how to implement it via schejulure?

**Comment by AdamClements** [comment]
The schedule function returns a future object, on which you can call cancel. You can do whatever you like with these futures, keep them in a list, put them in a map, whatever, so: 
    (def jobs {123 (schedule ...) 234 (schedule) ...})

```
(future-cancel (get jobs 123))
(future-cancelled? (get-jobs 123)) => false
```

Hope this helps!

**Comment by podviaznikov** [comment]
Thank you! Yes, that helps
