### ISSUE TITLE
Don't seem to be able to build a jar/uberjar via lein

### ISSUE THREAD

**Issue by Bigsy** [AdamClements/schejulure#5]
This could just me being dumb but I can get the schedule running fine using your example but if I have it loaded via def like that I am not able to build a jar/uberjar of my project via lein.

Do you have any tips to do this this?

I have tried launching it inside a defn as part of my app startup, didnt work, tried wrapping in (delay) and deref'in it... I can't quite work out whats going wrong so having trouble making it work.

Thanks.

**Comment by Bigsy** [comment]
Opps I could get this running in a defn as part of my app startup (something else caused me an issue) and this way I can build a jar.

I'll close this off :)

**Comment by AdamClements** [comment]
Glad you sorted it, let me know if you have any other issues.
